CREATE TABLE CLIENTE_JLM(
  NR_CPF        VARCHAR2(11),
  NM_CLIENTE    VARCHAR2(100),
  DT_NASCIMENTO DATE,
  CONSTRAINT PKCLIENTE_JLM PRIMARY KEY (NR_CPF)
); 

CREATE TABLE PRODUTO_JLM(
  CD_PRODUTO    NUMBER(10),
  DS_PRODUTO    VARCHAR2(100),
  VL_UNITARIO   NUMBER(15,2),
  CONSTRAINT PKPRODUTO_JLM PRIMARY KEY (CD_PRODUTO)
); 

CREATE TABLE VENDA_JLM(
  CD_VENDA       NUMBER(15),
  VL_TOTAL         NUMBER(15,2),
  QT_TOTAL        NUMBER(15,2),
  NR_CPFCLIENTE VARCHAR2(11),
  DT_VENDA      DATE,
  CONSTRAINT PKVENDA_JLM PRIMARY KEY (CD_VENDA),
  CONSTRAINT FKVENDA_CLIENTE_JLM FOREIGN KEY (NR_CPFCLIENTE) REFERENCES CLIENTE_JLM (NR_CPF)
);

CREATE TABLE ITEMVENDA_JLM(
CD_VENDA NUMBER(15),
CD_PRODUTO NUMBER(10),
VL_UNITPROD NUMBER(15,2),
QT_ADQUIRIDA NUMBER(15,2),
DT_RECORD DATE,
CONSTRAINT PKITEMVENDA_JLM PRIMARY KEY (CD_VENDA, CD_PRODUTO),
CONSTRAINT FKITEMVENDA_PRODUTO_JLM FOREIGN KEY (CD_PRODUTO) REFERENCES PRODUTO_JLM (CD_PRODUTO),
CONSTRAINT FKITEMVENDA_VENDA_JLM FOREIGN KEY (CD_VENDA) REFERENCES VENDA_JLM (CD_VENDA)
);


select * from CLIENTE_JLM;

SELECT v.CD_VENDA,
                  v.VL_TOTAL,
                  v.QT_TOTAL,
                  v.NR_CPFCLIENTE,
                  c.NM_CLIENTE,
                  p.DS_PRODUTO,
                  p.VL_UNITARIO,
                  v.DT_VENDA,
                  iv.QT_ADQUIRIDA
                FROM VENDA_JLM v,CLIENTE_JLM c,ITEMVENDA_JLM iv,PRODUTO_JLM p
                WHERE v.NR_CPFCLIENTE = c.NR_CPF
                 AND iv.CD_PRODUTO = p.CD_PRODUTO
                 AND iv.CD_VENDA   = v.CD_VENDA 
                 AND v.DT_VENDA = '12/07/2024'
                 ORDER BY CD_VENDA DESC;
                 
                 
SELECT VENDA_JLM.CD_VENDA,
                  VENDA_JLM.VL_TOTAL,
                  VENDA_JLM.QT_TOTAL,
                  VENDA_JLM.NR_CPFCLIENTE,
                  CLIENTE_JLM.NM_CLIENTE,
                  PRODUTO_JLM.DS_PRODUTO,
                  PRODUTO_JLM.VL_UNITARIO,
                  VENDA_JLM.DT_VENDA,
                  ITEMVENDA_JLM.QT_ADQUIRIDA
                FROM VENDA_JLM,CLIENTE_JLM,ITEMVENDA_JLM,PRODUTO_JLM
                WHERE VENDA_JLM.NR_CPFCLIENTE = CLIENTE_JLM.NR_CPF
                 AND ITEMVENDA_JLM.CD_PRODUTO = PRODUTO_JLM.CD_PRODUTO
                 AND ITEMVENDA_JLM.CD_VENDA   = VENDA_JLM.CD_VENDA AND TRUNC(VENDA_JLM.DT_VENDA) = TRUNC('12-JUL-24') ORDER BY CD_VENDA DESC
                 
                 
SELECT VENDA_JLM.CD_VENDA,
                  VENDA_JLM.VL_TOTAL,
                  VENDA_JLM.QT_TOTAL,
                  VENDA_JLM.NR_CPFCLIENTE,
                  CLIENTE_JLM.NM_CLIENTE,
                  PRODUTO_JLM.DS_PRODUTO,
                  PRODUTO_JLM.VL_UNITARIO,
                  VENDA_JLM.DT_VENDA,
                  ITEMVENDA_JLM.QT_ADQUIRIDA
                FROM VENDA_JLM,CLIENTE_JLM,ITEMVENDA_JLM,PRODUTO_JLM
                WHERE VENDA_JLM.NR_CPFCLIENTE = CLIENTE_JLM.NR_CPF
                 AND ITEMVENDA_JLM.CD_PRODUTO = PRODUTO_JLM.CD_PRODUTO
                 AND ITEMVENDA_JLM.CD_VENDA   = VENDA_JLM.CD_VENDA AND VENDA_JLM.DT_VENDA = '08-JUL-24'ORDER BY CD_VENDA DESC
